ERROR:root:An error occurred in file 'websockett.py', line 52: float() argument must be a string or a real number, not 'NoneType'
ERROR:root:An error occurred in file 'websockett.py', line 52: float() argument must be a string or a real number, not 'NoneType'
ERROR:root:An error occurred in file 'websockett.py', line 54: float() argument must be a string or a real number, not 'NoneType'
ERROR:root:An error occurred in file 'websockett.py', line 54: float() argument must be a string or a real number, not 'NoneType'
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'sl_strategy_2.py', line 82: cannot access local variable 'q_trailing_sl' where it is not associated with a value
ERROR:root:An error occurred in file 'websockett.py', line 54: float() argument must be a string or a real number, not 'NoneType'
